swagger: "2.0"
info:
  description: "CyberSchool API Doc...✌🏾"
  version: "1.0.0"
  title: "CyberSchool"
  license:
    name: "Github Repo"
    url: "https://github.com/Will-l3x/devops"
host: "localhost:3001"
basePath: "/api"
tags:
  - name: "Teacher"
    description: "All teacher-account related endpoints"
  - name: "Student"
    description: "All student-account related endpoints"
  - name: "Uploads"
    description: "All upload related endpoints"
  - name: "School Admin"
    description: "All schooladmin-account related endpoints"
schemes:
  - "http"
paths:
  /teacher/enrol_student:
    post:
      tags:
        - "Teacher"
      summary: "Adds a student to a class..."
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              classid:
                type: "integer"
              studentid:
                type: "integer"
              teacherid:
                type: "integer"
      responses:
        "405":
          description: "Invalid input"

  /teacher/new_material:
    post:
      tags:
        - "Teacher"
      summary: "Adds material to a class..."
      description: "In the body, the file property is a boolean thats used to tell server to prepare for a file upload, if false make sure obj field has an object that represents the material..."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              classid:
                type: "integer"
              teacherid:
                type: "integer"
              schoolid:
                type: "integer"
              materialname:
                type: "string"
              file:
                type: "boolean"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_material/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets a single material resource by ID..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "MaterialId of record to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_materials/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets all material resources of a class by classID..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ClassId of (material)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/new_assignment:
    post:
      tags:
        - "Teacher"
      summary: "Post an assignment for a class..."
      description: "In the body, the file property is a boolean thats used to tell server to prepare for a file upload, if false make sure obj field has an object that represents the material..."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              classid:
                type: "integer"
              teacherid:
                type: "integer"
              schoolid:
                type: "integer"
              assignmentname:
                type: "string"
              file:
                type: "boolean"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_assignment/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets a single assignment by ID..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "AssignmentID of record to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_assignments/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets all assignments of a class by classID..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ClassID of (assignment)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_submissions/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets all students' assignment submissions in an assignment..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "AssignmentID of (student_assignment)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/mark_assignment:
    put:
      tags:
        - "Teacher"
      summary: "Update the mark field of a student's submission for an assignment"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              student_assignmentid:
                type: "integer"
              mark:
                type: "integer"
      responses:
        "405":
          description: "Invalid input"

  /teacher/comment_assignment:
    put:
      tags:
        - "Teacher"
      summary: "Update the comment field of a student's submission for an assignment"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              student_assignmentid:
                type: "integer"
              comment:
                type: "string"
      responses:
        "405":
          description: "Invalid input"

  /teacher/new_reminder:
    post:
      tags:
        - "Teacher"
      summary: "Post a new reminder for all students in a class..."
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              classid:
                type: "integer"
              teacherid:
                type: "integer"
              enddate:
                type: "string"
              title:
                type: "string"
              message:
                type: "boolean"
      responses:
        "405":
          description: "Invalid input"

  /teacher/new_msg:
    post:
      tags:
        - "Teacher"
      summary: "Post a new message to a student in a class..."
      description: "Request object can also have 'to' and 'from' fields with full names as strings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              studentid:
                type: "integer"
              teacherid:
                type: "integer"
              title:
                type: "string"
              message:
                type: "boolean"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_msgs/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets all messages for a teacher..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "TeacherID of (messages)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_classes/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets all classes for a teacher..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "TeacherID of (class)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /teacher/get_students/{id}:
    get:
      tags:
        - "Teacher"
      summary: "Gets all students in a class for a teacher..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ClassID of (student)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /student/new_msg:
    post:
      tags:
        - "Student"
      summary: "Post a new message to a teacher in a class..."
      description: "Request object can also have 'to' and 'from' fields with full names as strings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              studentid:
                type: "integer"
              teacherid:
                type: "integer"
              title:
                type: "string"
              message:
                type: "boolean"
      responses:
        "405":
          description: "Invalid input"

  /student/get_msgs/{id}:
    get:
      tags:
        - "Student"
      summary: "Gets all messages for a student..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "StudentID of (messages)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"


  /schooladmin/teacher/{id}:
    get:
      tags:
        - "School Admin"
      summary: "Gets a single teacher..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "TeacherID of (teacher)record to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /schooladmin/teachers/{id}:
    get:
      tags:
        - "School Admin"
      summary: "Gets all teachers at a school..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "SchoolID on (teacher)records to return..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input"

  /schooladmin/add_teacher:
    post:
      tags:
        - "School Admin"
      summary: "Adds a new teachers to a school..."
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              schoolid:
                type: "integer"
              userid:
                type: "integer"
              firstname:
                type: "string"
              lastname:
                type: "string"
              datejoined:
                type: "date"
      responses:
        "405":
          description: "Invalid input"

  /schooladmin/del_teacher/{id}:
    delete:
      tags:
        - "School Admin"
      summary: "Deletes a teacher from a school..."
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "TeacherID on (teacher)records to delete..."
          required: true
          type: "integer"
          format: "int64"
      responses:
        "405":
          description: "Invalid input" 

  /schooladmin/update_teacher:
    put:
      tags:
        - "School Admin"
      summary: "Updates a teachers record..."
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Object required for route..."
          required: true
          schema:
            type: "object"
            properties:
              schoolid:
                type: "integer"
              userid:
                type: "integer"
              firstname:
                type: "string"
              lastname:
                type: "string"
              datejoined:
                type: "date"
      responses:
        "405":
          description: "Invalid input"       

