export const AdminContants = {
  GET_SUBSCRIBED_COURSES: "GET_SUBSCRIBED_COURSES",
  GET_SUBSCRIBE_COURSE: "GET_SUBSCRIBE_COURSE",
  SUBSCRIBE_COURSE: "SUBSCRIBE_COURSE",
  UNSUBSCRIBE_COURSE: "UNSUBSCRIBE_COURSE",
  GET_ALL_TEACHERS: "GET_ALL_TEACHERS",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
};

export default AdminContants;
