export const StreamContants = {
         GET_ALL_MEETINGS: "GET_ALL_MEETINGS",
         GET_ALL_MEETINGS_BY_CLASSID: "GET_ALL_MEETINGS_BY_CLASSID",
         GET_ALL_MEETINGS_BY_CREATORID: "GET_ALL_MEETINGS_BY_CREATORID",
         GET_MEETING: "GET_MEETING",
         START_MEETING: "START_MEETING",
         STOP_MEETING: "STOP_MEETING",
         CREATE_MEETING: "CREATE_MEETING",
       };

export default StreamContants;
