export const TeacherConstants = {
  GET_ALL_COURSES: "GET_ALL_COURSES",
  GET_ALL_PENDING: "GET_ALL_PENDING",
  GET_ALL_UNMARKED: "GET_ALL_UNMARKED",
  GET_LIVE_COURSE: "GET_LIVE_COURSE",
  CREATE_STREAM: "CREATE_STREAM",
  FETCH_STREAMS: "FETCH_STREAMS",
  FETCH_STREAM: "FETCH_STREAM",
  DELETE_STREAM: "DELETE_STREAM",
  EDIT_STREAM: "EDIT_STREAM",
};

export default TeacherConstants;
