export const UploadContants = {
  SET_UPLOAD_FILE: "SET_UPLOAD_FILE",
  SET_UPLOAD_PROGRESS: "SET_UPLOAD_PROGRESS",
  SUCCESS_UPLOAD_FILE: "SUCCESS_UPLOAD_FILE",
  FAILURE_UPLOAD_FILE: "FAILURE_UPLOAD_FILE",
  UPLOAD_FILE_CLEAR: "UPLOAD_FILE_CLEAR",
};

export default UploadContants;
