export const AdminContants = {
  GET_ALL_COURSES: "GET_ALL_COURSES",
  ADD_NEW_COURSE: "ADD_NEW_COURSE",
  ADD_COURSE_TOPIC: "ADD_COURSE_TOPIC",
  GET_COURSE_MATERIAL: "GET_COURSE_MATERIAL",
  ADD_COURSE_MATERIAL: "ADD_COURSE_MATERIAL",
  UPDATE_COURSE_MATERIAL: "UPDATE_COURSE_MATERIAL",
  DELETE_COURSE: "DELETE_COURSE",
  DELETE_COURSE_TOPIC: "DELETE_COURSE_TOPIC",
  GET_ALL_TEACHERS: "GET_ALL_TEACHERS",
  CONFIRM_TEACHER: "CONFIRM_TEACHER",
  GET_SUBCRIPTION_INFO: "GET_SUBCRIPTION_INFO",
  UPDATE_SUBCRIPTION_INFO: "UPDATE_SUBCRIPTION_INFO",
  GET_TOPIC_CONTENT: "GET_TOPIC_CONTENT",
};

export default AdminContants;
