export const ClassroomConstants = {
    GET_ALL_CLASSWORK: 'GET_ALL_CLASSWORK',
    GET_ALL_TEST_FOLDERS: 'GET_ALL_TEST_FOLDERS',
    GET_ALL_ASSIGNMENT_FOLDERS: 'GET_ALL_ASSIGNMENT_FOLDERS',
    GET_ALL_TEST_FILES: 'GET_ALL_TEST_FILES',
    GET_ALL_ASSIGNMENT_FILES: 'GET_ALL_ASSIGNMENT_FILES',
    ADD_CLASSROOM_MATERIAL: 'ADD_CLASSROOM_MATERIAL',
    DELETE_CLASSWORK: 'DELETE_CLASSWORK',
    ADD_TEACHER: 'ADD_TEACHER',
    ADD_STUDENT: 'ADD_STUDENT',
    UPDATE_STUDENT_MARKS: 'UPDATE_STUDENT_MARKS',
    UPLOAD_MARKED_CLASSWORK: 'UPLOAD_MARKED_CLASSWORK'
}